baseURL = 'https://noah-b-reef.github.io/personal-website/'
locale = 'en-us'
title = 'Noah Reef - Personal Website'
theme = 'hugo-xterm'

[taxonomies]
  tag = "tags"

[params]
  showMenuItems = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$'], ['\(', '\)']]
    [markup.goldmark.renderer]
      unsafe = true
