baseURL = 'https://noah-reef.net/'
locale = 'en-us'
title = 'My New Hugo Project'
theme = 'hugo-xterm'

[params]
  showMenuItems = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
